name: Build and Deploy Docker Image

on:
  push:
    paths:
      - 'docker-frontend-backend-db/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker images
      run: |
        cd docker-frontend-backend-db
        docker-compose build
        docker-compose push

    - name: SSH into VM and pull Docker image
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: 192.168.6.236
        username: joe
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull your-dockerhub-username/fileupdater:latest
          ./start_container.sh
