name: Deploy to VM

on:
  push:
    branches:
      - main  # Adjust this if you want to trigger on a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: SSH into VM and pull repository
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: 192.168.6.236
        username: joe
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/file  # Ensure this is the directory where you want to pull the repository
          git pull https://github.com/Jivko03/Fileupdater.git

