#!bash/bin
name: Deploy to Debian VM

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy files to VM
        run: |
          ssh-keyscan -H 51.120.122.186 >> ~/.ssh/known_hosts
          ssh joe@192.168.6.236 'bash -s' < ./deploy_script.sh
          rsync -avz --delete --exclude='.git' -e "ssh -o StrictHostKeyChecking=no" ./ joe@192.168.6.236:~/file/
        env:
            SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
